platform :ios,"7.0"
inhibit_all_warnings!

target ‘MDKinderGarten’ do
pod 'YTKNetwork’,’~>1.3.0’

pod 'SDWebImage’,’~>3.8.2’

pod 'MBProgressHUD’,’~>1.0.0’

pod 'Masonry',’~>1.0.2’

pod 'MJExtension',’~>3.0.13’

pod 'MJRefresh',’~>3.1.12’

pod 'FMDB',’~>2.6.2’

pod 'SAMKeychain',’~>1.5.2’

pod 'UMengAnalytics-NO-IDFA',’~>4.1.1’

pod 'SDCycleScrollView','~> 1.65’

pod 'IQKeyboardManager',’~>3.3.7’

pod 'IDMPhotoBrowser’,’~>1.9.1’

end
